#!/usr/bin/env bash
# scripts/30-runtipi-config.sh - Point Runtipi at home.arpa and publish the
# dashboard on SERVER_DOMAIN.
#
# THE DASHBOARD HOSTNAME COMPROMISE
# ---------------------------------
# Runtipi's dashboard router binds the BARE local domain:
#     traefik.http.routers.dashboard-local.rule: Host(`${LOCAL_DOMAIN}`)
# (docker-compose.prod.yml), while apps bind `<subdomain>.${LOCAL_DOMAIN}`
# (traefik-labels.builder.ts).
#
# So LOCAL_DOMAIN=home.arpa natively gives:
#     http://home.arpa        -> dashboard
#     http://nomad.home.arpa  -> Project NOMAD
# but NOT http://server.home.arpa.
#
# Setting LOCAL_DOMAIN=server.home.arpa would fix the dashboard and break every
# app (they would become nomad.server.home.arpa), so that is the wrong trade.
#
# Instead we keep LOCAL_DOMAIN=home.arpa and add ONE extra Traefik router via
# the file provider that Runtipi's Traefik already watches
# (/etc/traefik/dynamic, watch: true — see assets/traefik/traefik.yml). Runtipi
# only ever writes dynamic.yml into that directory (app.service.ts), so an
# additional file is an extension point, not a file we are fighting over.
# The router forwards to `dashboard@docker`, the service Runtipi's own labels
# define, so we are not duplicating its configuration — only aliasing it.
#
# Result: the dashboard answers on BOTH home.arpa and server.home.arpa.
#
# Runnable standalone:  sudo scripts/30-runtipi-config.sh

US_LIB_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../lib" && pwd)"
# shellcheck source=lib/common.sh
source "${US_LIB_DIR}/common.sh"
# shellcheck source=lib/config.sh
source "${US_LIB_DIR}/config.sh"
# shellcheck source=lib/docker.sh
source "${US_LIB_DIR}/docker.sh"
# shellcheck source=lib/versions.sh
source "${US_LIB_DIR}/versions.sh"
# shellcheck source=lib/runtipi.sh
source "${US_LIB_DIR}/runtipi.sh"

us_init "runtipi-config"
us_require_root
us_config_load

us_section "Runtipi configuration"

[[ -x "$(us_runtipi_cli)" ]] ||
  us_die "Runtipi CLI not found. Run scripts/20-runtipi.sh first."

needs_restart=0

# --- Local domain ----------------------------------------------------------
current_domain="$(us_runtipi_env_get LOCAL_DOMAIN 2>/dev/null || printf '')"
us_info "Setting Runtipi local domain to ${LOCAL_DOMAIN} (currently: ${current_domain:-unset})"

if us_runtipi_configure_local_domain; then
  needs_restart=1
fi
[[ "$current_domain" == "$LOCAL_DOMAIN" ]] || needs_restart=1

# --- Dashboard alias router ------------------------------------------------
# entryPoints/tls are conditional on ENABLE_LOCAL_HTTPS so the same generator
# serves the plain-HTTP milestone and a later HTTPS one.
if us_config_is_true "$ENABLE_LOCAL_HTTPS"; then
  read -r -d '' alias_config <<EOF || true
# Managed by ${US_PROJECT_NAME}. Publishes the Runtipi dashboard on
# ${SERVER_DOMAIN} in addition to its native ${LOCAL_DOMAIN} binding.
# Regenerated by scripts/30-runtipi-config.sh; edits here will be overwritten.
http:
  routers:
    ${US_PROJECT_NAME}-dashboard-alias-insecure:
      rule: "Host(\`${SERVER_DOMAIN}\`)"
      entryPoints:
        - web
      service: "dashboard@docker"
      middlewares:
        - redirect-to-https@docker
    ${US_PROJECT_NAME}-dashboard-alias:
      rule: "Host(\`${SERVER_DOMAIN}\`)"
      entryPoints:
        - websecure
      service: "dashboard@docker"
      tls: {}
EOF
else
  read -r -d '' alias_config <<EOF || true
# Managed by ${US_PROJECT_NAME}. Publishes the Runtipi dashboard on
# ${SERVER_DOMAIN} in addition to its native ${LOCAL_DOMAIN} binding.
# Regenerated by scripts/30-runtipi-config.sh; edits here will be overwritten.
http:
  routers:
    ${US_PROJECT_NAME}-dashboard-alias:
      rule: "Host(\`${SERVER_DOMAIN}\`)"
      entryPoints:
        - web
      service: "dashboard@docker"
EOF
fi

if printf '%s\n' "$alias_config" |
  us_runtipi_write_dynamic "${US_PROJECT_NAME}-dashboard.yml"; then
  us_ok "Dashboard alias router for ${SERVER_DOMAIN} written"
  # Traefik's file provider watches this directory, so no restart is needed.
else
  us_debug "Dashboard alias router already current"
fi

# --- Apply -----------------------------------------------------------------
# LOCAL_DOMAIN is baked into container labels at generation time, so a change
# needs Runtipi to regenerate and recreate. The file-provider router does not.
if ((needs_restart)) && [[ "$US_DRY_RUN" != "1" ]]; then
  us_info "Local domain changed; restarting Runtipi to regenerate routing"
  us_runtipi_start
  us_runtipi_wait_api 300 || us_die "Runtipi did not come back after the domain change."
fi

if [[ "$US_DRY_RUN" != "1" ]]; then
  effective="$(us_runtipi_env_get LOCAL_DOMAIN 2>/dev/null || printf '')"
  if [[ "$effective" == "$LOCAL_DOMAIN" ]]; then
    us_ok "Runtipi LOCAL_DOMAIN=${effective}"
  else
    us_warn "Runtipi reports LOCAL_DOMAIN='${effective}', expected '${LOCAL_DOMAIN}'."
    us_warn "Check $(us_runtipi_settings_file)"
  fi
  us_info "Dashboard will answer on http://${LOCAL_DOMAIN} and http://${SERVER_DOMAIN}"
fi
