#!/usr/bin/env bash
# tools/publish-appstore.sh - Publish appstore/apps/ to the `appstore` branch.
#
# WHY THIS EXISTS
# ---------------
# Runtipi resolves an app store's apps at <repo-root>/apps
# (app-store-files-manager.ts: path.join(dataDir, 'repos', slug, 'apps')) and
# clones it with isomorphic-git over HTTP(S) — so a local path or file:// URL
# will not work, and apps/ must be at the repository ROOT.
#
# This repository keeps its definitions in appstore/apps/ so they live beside
# the installer that deploys them. Those two facts are reconciled by publishing
# the contents of appstore/ to an orphan branch where apps/ IS the root.
# Runtipi selects it with the /tree/<branch> URL suffix, which its
# getRepoBaseUrlAndBranch() parses (repos.helpers.ts).
#
# The branch is orphan and rewritten each time: it is a published artifact, not
# a history worth preserving.
#
#   ./tools/publish-appstore.sh              validate, then publish
#   ./tools/publish-appstore.sh --dry-run    show what would be published
#   ./tools/publish-appstore.sh --branch X   publish to a different branch

set -Eeuo pipefail

US_ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
US_LIB_DIR="${US_ROOT_DIR}/lib"
# shellcheck source=lib/common.sh
source "${US_LIB_DIR}/common.sh"

us_init "publish-appstore"
us_require_cmds git

branch="appstore"
dry=0
while (($#)); do
  case "$1" in
    --branch)
      branch="${2:?--branch requires a value}"
      shift 2
      ;;
    --dry-run)
      dry=1
      shift
      ;;
    -h | --help)
      sed -n '2,25p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) us_die "Unknown option: $1" ;;
  esac
done

cd "$US_ROOT_DIR"

git rev-parse --git-dir >/dev/null 2>&1 || us_die "Not a git repository."

# --- Validate before publishing -------------------------------------------
us_section "Validating before publish"
"${US_ROOT_DIR}/tools/validate-appstore.sh" ||
  us_die "App store validation failed; refusing to publish."

# --- Check the working tree ------------------------------------------------
if [[ -n "$(git status --porcelain appstore/ 2>/dev/null)" ]]; then
  us_warn "appstore/ has uncommitted changes. They WILL be published, but the"
  us_warn "commit on ${branch} will reference a source commit that lacks them."
fi

origin="$(git remote get-url origin 2>/dev/null || true)"
[[ -n "$origin" ]] || us_die "No 'origin' remote; cannot publish."

source_commit="$(git rev-parse --short HEAD)"

us_section "Publishing app store"
us_info "Source:  ${US_ROOT_DIR}/appstore/apps"
us_info "Branch:  ${branch}"
us_info "Remote:  ${origin}"

if ((dry)); then
  us_info "DRY-RUN: would publish these apps:"
  for d in appstore/apps/*/; do
    [[ -d "$d" ]] && printf '    %s\n' "$(basename "$d")" >&2
  done
  https_url="${origin%.git}"
  https_url="${https_url/git@github.com:/https://github.com/}"
  us_info "Store URL would be: ${https_url}/tree/${branch}"
  exit 0
fi

# Build the branch content in a temporary worktree so the working tree is
# never disturbed — this tool must be safe to run mid-development.
tmp="$(mktemp -d)"
cleanup() { rm -rf "$tmp"; }
trap cleanup EXIT

cp -a appstore/. "$tmp/"

# Guard against publishing anything that should not leave the repo.
if find "$tmp" -name '*.env' -o -name 'secrets*' -o -name '*.key' | grep -q .; then
  us_die "Refusing to publish: found env/secret/key files under appstore/."
fi

pushd "$tmp" >/dev/null
git init -q
git checkout -q -b "$branch"

cat >README.md <<EOF
# u-server app store

Generated by \`tools/publish-appstore.sh\` from the \`appstore/\` directory of
the u-server repository. **Do not edit this branch directly** — it is rewritten
on every publish.

Source commit: \`${source_commit}\`

Register this store with Runtipi:

    runtipi appstore add u-server ${origin%.git}/tree/${branch}

Apps in this store:

$(for d in apps/*/; do
  [[ -d "$d" ]] || continue
  name="$(jq -r '.name // "?"' "${d}config.json" 2>/dev/null || echo '?')"
  avail="$(jq -r '.available // false' "${d}config.json" 2>/dev/null || echo '?')"
  printf -- '- **%s** (`%s`) — available: %s\n' "$name" "$(basename "$d")" "$avail"
done)
EOF

git add -A
git -c user.name="${GIT_AUTHOR_NAME:-u-server}" \
  -c user.email="${GIT_AUTHOR_EMAIL:-u-server@localhost}" \
  commit -q -m "Publish app store from ${source_commit}"

us_info "Pushing to ${branch} (force: this branch is a generated artifact)"
git push -q --force "$origin" "${branch}:${branch}" ||
  us_die "Push failed. Check your credentials and write access to ${origin}."
popd >/dev/null

https_url="${origin%.git}"
https_url="${https_url/git@github.com:/https://github.com/}"

us_ok "Published to ${branch}"
us_info "App store URL:"
us_info "    ${https_url}/tree/${branch}"
us_info ""
us_info "On the server, register or refresh it:"
us_info "    sudo ./install.sh --stage 60-appstore"
us_info "    sudo ./update.sh appstore"
